global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'secure-scrape-agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3002']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
